name: Update Pacman Repo

on:
  push:
    paths:
      - "x86_64/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run repo-add in Arch Linux Docker
        run: |
          docker run --rm -v $PWD:/repo -w /repo archlinux:latest /bin/bash -c "
          pacman -Sy --noconfirm arch-install-scripts
          cd x86_64
          rm -f *.db *.db.tar.gz *.files *.files.tar.gz
          repo-add hona-repo.db.tar.gz *.pkg.tar.zst
          "

      - name: Commit updated repo files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add x86_64/*.db* x86_64/*.files*
          git commit -m 'Auto-update repo db' || echo 'No changes to commit'
          git push
