name: Update pacman repo

on:
  push:
    paths:
      - "x86_64/**"   # tylko gdy coś się zmienia w katalogu z paczkami

jobs:
  build:
    runs-on: ubuntu-latest   # możemy zostawić Ubuntu, ale użyjemy Dockera
    steps:
      - uses: actions/checkout@v3

      - name: Setup Arch Linux container
        run: |
          docker run --rm -v $PWD:/repo -w /repo archlinux:latest /bin/bash -c "
          pacman -Sy --noconfirm pacman
          pacman -S --noconfirm arch-install-scripts
          cd x86_64
          rm -f *.db *.db.tar.gz *.files *.files.tar.gz
          repo-add hona-repo.db.tar.gz *.pkg.tar.zst
          "
